package io.github.mcbianconi.quintkonnect.example.tictactoe

import io.github.mcbianconi.quintkonnect.TypedState
import kotlinx.serialization.serializer

// TictactoeSpec is generated by KSP from tictactoe.qnt's typed IR (qk-ixox).
class TicTacToeState : TypedState<TicTacToeDriver, TictactoeSpec.State>(serializer()) {
    override fun extractFromDriver(driver: TicTacToeDriver): TictactoeSpec.State {
        // board[col][row] = cell at Quint coord (col, row), 1-indexed
        // driver.game.board[rowIdx][colIdx] = cell at (col=colIdx+1, row=rowIdx+1)
        val board = buildMap<Long, Map<Long, TictactoeSpec.Square>> {
            for (colIdx in 0..2) {
                val col = (colIdx + 1).toLong()
                val rows = buildMap<Long, TictactoeSpec.Square> {
                    for (rowIdx in 0..2) {
                        val row = (rowIdx + 1).toLong()
                        val cell = driver.game.board[rowIdx][colIdx]
                        put(row, if (cell == null) TictactoeSpec.Square.Empty else TictactoeSpec.Square.Occupied(cell.toSpec()))
                    }
                }
                put(col, rows)
            }
        }
        return TictactoeSpec.State(board = board, nextTurn = driver.game.nextTurn.toSpec())
    }

    private fun Player.toSpec(): TictactoeSpec.Player = when (this) {
        Player.X -> TictactoeSpec.Player.X
        Player.O -> TictactoeSpec.Player.O
    }
}
