package io.github.mcbianconi.quintkonnect.example.rockpaperscissors

import io.github.mcbianconi.quintkonnect.TypedState
import kotlinx.serialization.serializer

// RockPaperScissorsSpec is generated by KSP from rock-paper-scissors.qnt's typed IR (qk-ixox).
class RpsGameState : TypedState<RockPaperScissorsDriver, RockPaperScissorsSpec.State>(serializer()) {
    override fun extractFromDriver(driver: RockPaperScissorsDriver): RockPaperScissorsSpec.State =
        RockPaperScissorsSpec.State(
            p1State = driver.game.p1Move.toSpec(),
            p2State = driver.game.p2Move.toSpec(),
            status = driver.game.status.toSpec(),
        )
}

// Shared with the buggy/ and partialstate/ drivers, which replay the same spec.
internal fun RockPaperScissorsSpec.Move.toMove(): Move = when (this) {
    RockPaperScissorsSpec.Move.Init -> Move.INIT
    RockPaperScissorsSpec.Move.Rock -> Move.ROCK
    RockPaperScissorsSpec.Move.Paper -> Move.PAPER
    RockPaperScissorsSpec.Move.Scissors -> Move.SCISSORS
}

internal fun Move.toSpec(): RockPaperScissorsSpec.Move = when (this) {
    Move.INIT -> RockPaperScissorsSpec.Move.Init
    Move.ROCK -> RockPaperScissorsSpec.Move.Rock
    Move.PAPER -> RockPaperScissorsSpec.Move.Paper
    Move.SCISSORS -> RockPaperScissorsSpec.Move.Scissors
}

internal fun GameStatus.toSpec(): RockPaperScissorsSpec.GameStatus = when (this) {
    is GameStatus.Started -> RockPaperScissorsSpec.GameStatus.Started
    is GameStatus.Pending -> RockPaperScissorsSpec.GameStatus.Pending
    is GameStatus.Draw -> RockPaperScissorsSpec.GameStatus.Draw
    is GameStatus.Winner -> RockPaperScissorsSpec.GameStatus.Winner(player.toSpec())
}

private fun Player.toSpec(): RockPaperScissorsSpec.Player = when (this) {
    Player.PLAYER1 -> RockPaperScissorsSpec.Player.PLAYER1
    Player.PLAYER2 -> RockPaperScissorsSpec.Player.PLAYER2
}
